<?php

/**
 * @file
 * Form filter API ( Example ).
 *
 * Example work module.
 */

/*
 * Name form with filters.
 */
define('FORMFILTERAPI_EXAMPLE_FORM_NAME', 'formfilterapi_example');

/**
 * Implements hook_menu().
 */
function formfilterapi_example_menu() {
  $items['formfilterapi_example'] = array(
    'title' => 'Form filter API',
    'page callback' => 'formfilterapi_example_page',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Example page.
 */
function formfilterapi_example_page() {
  $form = formfilterapi_get_form(FORMFILTERAPI_EXAMPLE_FORM_NAME);

  $filters = formfilterapi_build_filter_query(FORMFILTERAPI_EXAMPLE_FORM_NAME);

  $sql = 'SELECT n.nid FROM {node} n ' . $filters['join'] . ' ' . $filters['where'] . ' ORDER BY n.created DESC LIMIT 5';
  $result = db_query($sql, $filters['args']);
  $nodes = $result->fetchAll();

  $output_nodes = drupal_render($form);

  foreach ($nodes as $node) {
    $n2 = node_load($node->nid);
    $view = node_view($n2, 'teaser');
    $output_nodes .= drupal_render($view);
  }

  return $output_nodes;
}

/**
 * Implements hook_formfilterapi().
 */
function formfilterapi_example_formfilterapi($op, $session_name, &$sessvals = array()) {
  switch ($op) {
    case 'pre_query':
      if ($session_name == FORMFILTERAPI_EXAMPLE_FORM_NAME) {
        // For WHERE LIKE.
        $sessvals['title'] = '%' . $sessvals['title'] . '%';
      }
      break;

    case 'filters':
      if ($session_name == FORMFILTERAPI_EXAMPLE_FORM_NAME) {
        $form['title'] = array(
          '#type' => 'textfield',
          '#title' => t('Title'),
          '#where' => "n.title LIKE ?",
        );

        $form['type'] = array(
          '#type' => 'select',
          '#title' => t('Type'),
          '#options' => formfilterapi_example_node_types(),
          '#where' => "n.type = ?",
        );

        $form['uid'] = array(
          '#type' => 'select',
          '#title' => t('User'),
          '#options' => formfilterapi_example_users(),
          '#where' => "n.uid = ?",
        );

        return $form;
      }
      break;
  }
}

/**
 * List node types for select.
 *
 * @return array
 *   Node types.
 */
function formfilterapi_example_node_types() {
  $types = node_type_get_types();
  $result = array();

  foreach ($types as $type) {
    $result[$type->type] = $type->name;
  }

  return $result;
}

/**
 * List users for select.
 *
 * @return array
 *   Users.
 */
function formfilterapi_example_users() {
  $users = db_select('users', 'u')
    ->fields('u', array('uid', 'name'))
    ->condition('uid', 0, '!=')
    ->range(0, 10)
    ->orderBy('uid', 'DESC')
    ->execute()
    ->fetchAll();
  $result = array();

  foreach ($users as $user) {
    $result[$user->uid] = $user->name;
  }

  return $result;
}
